CREATE TABLE IF NOT EXISTS PERSON (
	PERSON_ID VARCHAR(36) PRIMARY KEY NOT NULL,
	FIRST_NAME VARCHAR(30),
	LAST_NAME VARCHAR(30),
	AGE INTEGER
);

CREATE TABLE IF NOT EXISTS PRODUCT (
	PRODUCT_ID VARCHAR(36) PRIMARY KEY NOT NULL,
	PRODUCT_NAME VARCHAR(30),
	PRODUCT_DESCRIPTION VARCHAR(30),
	PRICE NUMERIC
);

CREATE TABLE IF NOT EXISTS PURCHASE_ORDER (
	ORDER_ID VARCHAR(36) PRIMARY KEY NOT NULL,
	ORDER_TOTAL NUMERIC
);

CREATE TABLE IF NOT EXISTS PERSON_ORDER_PRODUCT (
	ORDER_ID VARCHAR(36),
	PERSON_ID VARCHAR(36),
	PRODUCT_ID VARCHAR(36)
)